### ISSUE TITLE
Too long project subtitle description

### ISSUE THREAD

**Issue by omichel** [ChloeEmmaA/open-sympto#6]
The subtitle description text that @ChloeEmmaA entered seems too long, as it can be seen on our project home page: https://github.com/ChloeEmmaA/open-sympto. As you can see, it is truncated. I believe such a text should be one sentence only, maybe two and a more complete description could go in the `README.md` file.

**Comment by ChloeEmmaA** [comment]
Ok, I changed it.

**Comment by omichel** [comment]
Thanks!
